Fwmt 990 secondary perfomance testing
ONSdigital/census-fwmt-rm-adapter pull request #30
Opened 2019-03-26 11:01 UTC by SteveScorfield

Updated to work with performance suite

2019-03-27 12:50 UTC, JacobHarrisonQA commented
May need to increment the event lib version in gradle

2019-03-28 11:52 UTC, sdiaz1000 requested changes

2019-03-28 11:52 UTC, spdiaz1000 commented on src/main/java/uk/gov/ons/census/fwmt/rmadapter/service/impl/MessageListenerService.java
> +
For this type of task I think we dont need it in the ervice layer, service layer is more for business functionality. I think its safe to move the simpleMessageListenerContainer.start(); and stop to the controller class and delete this class. But well remembered

2019-03-28 13:54 UTC, sdiaz1000 approved these changes

2019-03-28 13:55 UTC, sdiaz1000 approved these changes

2019-03-28 13:55 UTC, merged